IF EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N'Samples')
 DROP DATABASE Samples;
GO


CREATE DATABASE [Samples]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Samples', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Samples.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Samples_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Samples_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Samples].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Samples] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Samples] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Samples] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Samples] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Samples] SET ARITHABORT OFF 
GO

ALTER DATABASE [Samples] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Samples] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Samples] SET AUTO_UPDATE_STATISTICS OFF 
GO

ALTER DATABASE [Samples] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Samples] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Samples] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Samples] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Samples] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Samples] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Samples] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Samples] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Samples] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Samples] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Samples] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Samples] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Samples] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Samples] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Samples] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Samples] SET  MULTI_USER 
GO

ALTER DATABASE [Samples] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [Samples] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Samples] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Samples] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Samples] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Samples] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Samples] SET QUERY_STORE = ON
GO

ALTER DATABASE [Samples] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Samples] SET  READ_WRITE 
GO


